import { supabase } from '../lib/supabase';

const fromRow=(r,index=0)=>({id:r.id,numero:index+1,atleta1Id:r.athlete_a_id,atleta2Id:r.athlete_b_id,modalidade:r.modality==='gi'?'Gi':'No-Gi',estilo:r.fight_style,status:r.status==='finished'?'Finalizada':'Agendada',observacoes:r.notes||'',createdAt:r.created_at,resultado:r.status==='finished'?{vencedorId:r.winner_id,forma:r.victory_method,finalizacao:r.submission,texto:r.winner_id?`Vitória por ${(r.victory_method||'resultado').toLowerCase()}${r.submission?` (${r.submission})`:''}`:'Luta encerrada sem vencedor'}:null});
const toRow=f=>({athlete_a_id:f.atleta1Id,athlete_b_id:f.atleta2Id,modality:f.modalidade==='Gi'?'gi':'nogi',fight_style:f.estilo,status:f.status==='Finalizada'?'finished':'scheduled',winner_id:f.resultado?.vencedorId||null,victory_method:f.status==='Finalizada'?(f.resultado?.forma||'Outra'):null,submission:f.resultado?.finalizacao||null,notes:f.observacoes||null,updated_at:new Date().toISOString()});
const fail=(error,message)=>{if(error)throw new Error(message)};
export async function getFights(){const {data,error}=await supabase.from('fights').select('*').order('created_at');fail(error,'Não foi possível carregar as lutas.');return data.map(fromRow)}
export async function getFightById(id){const {data,error}=await supabase.from('fights').select('*').eq('id',id).single();fail(error,'Não foi possível carregar a luta.');return fromRow(data)}
export async function createFight(fight){const {data,error}=await supabase.from('fights').insert(toRow(fight)).select().single();fail(error,'Não foi possível criar a luta.');return fromRow(data)}
export async function updateFight(fight){const {data,error}=await supabase.from('fights').update(toRow(fight)).eq('id',fight.id).select().single();fail(error,'Não foi possível atualizar a luta.');return fromRow(data)}
export async function deleteFight(id){const {error}=await supabase.from('fights').delete().eq('id',id);fail(error,'Não foi possível excluir a luta.')}
export async function finishFight(id,result){const {data,error}=await supabase.from('fights').update({status:'finished',winner_id:result.vencedorId||null,victory_method:result.forma,submission:result.finalizacao||null,notes:result.observacoes||null,updated_at:new Date().toISOString()}).eq('id',id).select().single();fail(error,'Não foi possível salvar o resultado.');return fromRow(data)}
