import { useEffect, useState } from 'react';
import { AlertTriangle, Trophy } from 'lucide-react';
import Sidebar from './components/Sidebar'; import Header from './components/Header'; import Modal from './components/Modal';
import Login from './pages/Login'; import Dashboard from './pages/Dashboard'; import Athletes from './pages/Athletes'; import AthleteForm from './pages/AthleteForm'; import CreateFight from './pages/CreateFight'; import Fights from './pages/Fights';
import { isSupabaseConfigured } from './lib/supabase';
import { getSession, login, logout, onAuthStateChange } from './services/authService';
import * as athleteService from './services/athleteService'; import * as fightService from './services/fightService';
import { checkSupabaseConnection } from './services/healthService';

const pathToPage={'/dashboard':'dashboard','/athletes':'athletes','/fights/new':'create','/fights':'fights'};
const pageToPath={dashboard:'/dashboard',athletes:'/athletes',create:'/fights/new',fights:'/fights'};

export default function App(){
 const[session,setSession]=useState(undefined);const[page,setPageState]=useState(()=>pathToPage[location.pathname]||'dashboard');const[menu,setMenu]=useState(false);const[athletes,setAthletes]=useState([]);const[fights,setFights]=useState([]);const[modal,setModal]=useState(null);const[prefill,setPrefill]=useState('');const[toast,setToast]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(true);const[health,setHealth]=useState(null);
 function setPage(next){setPageState(next);history.pushState({},'',pageToPath[next]);}
 function notify(message){setToast(message);setTimeout(()=>setToast(''),2800)}
 async function loadData(){setLoading(true);setError('');try{const[a,f,h]=await Promise.all([athleteService.getAthletes(),fightService.getFights(),checkSupabaseConnection()]);setAthletes(a);setFights(f);setHealth(h)}catch(err){setError(err.message)}finally{setLoading(false)}}
 useEffect(()=>{let active=true;getSession().then(s=>{if(active)setSession(s)}).catch(err=>{setError(err.message);setSession(null)});const unsubscribe=onAuthStateChange(s=>setSession(s));const pop=()=>setPageState(pathToPage[location.pathname]||'dashboard');addEventListener('popstate',pop);return()=>{active=false;unsubscribe();removeEventListener('popstate',pop)}},[]);
 useEffect(()=>{if(session){if(location.pathname==='/login')history.replaceState({},'','/dashboard');loadData()}else if(session===null&&location.pathname!=='/login')history.replaceState({},'','/login')},[session]);
 async function doLogout(){try{await logout()}catch(err){notify(err.message)}}
 function athleteForm(initial){setModal({title:initial?'Editar atleta':'Novo atleta',body:<AthleteForm initial={initial} onCancel={()=>setModal(null)} onSave={async data=>{if(initial)await athleteService.updateAthlete(data);else await athleteService.createAthlete(data);await loadData();setModal(null);notify(initial?'Atleta atualizado com sucesso.':'Atleta cadastrado com sucesso.')}}/>})}
 function removeAthlete(a){const linked=fights.some(f=>f.atleta1Id===a.id||f.atleta2Id===a.id);setModal({title:'Excluir atleta',body:<Confirm warning={linked?'Este atleta possui lutas relacionadas e não poderá ser excluído até que elas sejam removidas.':''} text={`Tem certeza que deseja excluir ${a.nome}?`} action="Excluir atleta" disabled={linked} onCancel={()=>setModal(null)} onConfirm={async()=>{try{await athleteService.deleteAthlete(a.id);await loadData();setModal(null);notify('Atleta excluído com sucesso.')}catch(err){notify(err.message)}}}/>})}
 function viewAthlete(a){setModal({title:'Detalhes do atleta',body:<div className="detail"><div className="initials hero">{a.nome.split(' ').map(n=>n[0]).slice(0,2)}</div><h2>{a.nome}</h2><p>{a.idade} anos • {a.peso} kg • Faixa {a.faixa}</p><div className="detail-grid"><span><b>Categoria</b>{a.categoria}</span><span><b>Modalidade</b>{a.modalidade}</span><span><b>Divisão</b>{a.sexo}</span><span><b>Academia</b>{a.academia||'—'}</span></div>{a.observacoes?<div className="note"><b>Observações</b>{a.observacoes}</div>:null}<button className="btn primary full" onClick={()=>startMatch(a.id)}>Encontrar adversário</button></div>})}
 function startMatch(id){setPrefill(id);setPage('create');setModal(null)}
 async function commitFight(data){try{await fightService.createFight(data);await loadData();setPage('fights');setPrefill('');setModal(null);notify('Luta criada com sucesso.')}catch(err){notify(err.message)}}
 function addFight(data,warnings){if(warnings.length)setModal({title:'Confirmar confronto',body:<Confirm warning={warnings.join(' • ')} text="Existem diferenças relevantes. A decisão final é do organizador." action="Confirmar luta" onCancel={()=>setModal(null)} onConfirm={()=>commitFight(data)}/>});else commitFight(data)}
 function resultFight(f){const a1=athletes.find(a=>a.id===f.atleta1Id),a2=athletes.find(a=>a.id===f.atleta2Id);setModal({title:'Informar resultado',body:<ResultForm a1={a1} a2={a2} onCancel={()=>setModal(null)} onSave={async result=>{await fightService.finishFight(f.id,result);await loadData();setModal(null);notify('Resultado salvo com sucesso.')}}/>})}
 function editFight(f){setModal({title:'Editar luta',body:<FightEdit fight={f} athletes={athletes} onCancel={()=>setModal(null)} onSave={async data=>{await fightService.updateFight(data);await loadData();setModal(null);notify('Luta atualizada com sucesso.')}}/>})}
 function removeFight(f){setModal({title:'Excluir luta',body:<Confirm text="Tem certeza que deseja excluir esta luta? Os atletas não serão excluídos." action="Excluir luta" onCancel={()=>setModal(null)} onConfirm={async()=>{try{await fightService.deleteFight(f.id);await loadData();setModal(null);notify('Luta excluída com sucesso.')}catch(err){notify(err.message)}}}/>})}
 if(session===undefined)return <div className="boot">Carregando...</div>;
 if(!session)return <Login onLogin={login} configurationPending={!isSupabaseConfigured}/>;
 return <div className="app"><Sidebar page={page} setPage={setPage} onLogout={doLogout} open={menu} setOpen={setMenu}/><main className="main"><Header page={page}/><div className="content">{error?<div className="form-error page-error">{error} <button onClick={loadData}>Tentar novamente</button></div>:null}{loading?<div className="empty large">Carregando dados...</div>:<>{page==='dashboard'?<Dashboard athletes={athletes} fights={fights} setPage={setPage} startMatch={startMatch} health={health}/>:null}{page==='athletes'?<Athletes athletes={athletes} fights={fights} onAdd={()=>athleteForm()} onEdit={athleteForm} onDelete={removeAthlete} onView={viewAthlete} onMatch={startMatch}/>:null}{page==='create'?<CreateFight key={prefill} athletes={athletes} fights={fights} prefill={prefill} onCreate={addFight}/>:null}{page==='fights'?<Fights athletes={athletes} fights={fights} onResult={resultFight} onEdit={editFight} onDelete={removeFight}/>:null}</>}</div></main>{modal?<Modal title={modal.title} onClose={()=>setModal(null)} wide>{modal.body}</Modal>:null}{toast?<div className="toast">✓ {toast}</div>:null}</div>
}
function Confirm({text,warning,action,onCancel,onConfirm,disabled}){const[busy,setBusy]=useState(false);async function confirm(){setBusy(true);await onConfirm();setBusy(false)}return <div className="confirm">{warning?<div className="warning"><AlertTriangle/><div><b>Atenção</b><small>{warning}</small></div></div>:null}<p>{text}</p><div className="form-actions"><button className="btn ghost" onClick={onCancel}>Cancelar</button><button disabled={disabled||busy} className="btn danger-fill" onClick={confirm}>{busy?'Aguarde...':action}</button></div></div>}
function ResultForm({a1,a2,onCancel,onSave}){const[winner,setWinner]=useState('draw');const[method,setMethod]=useState('Finalização');const[finish,setFinish]=useState('');const[obs,setObs]=useState('');const[error,setError]=useState('');async function submit(e){e.preventDefault();try{await onSave({vencedorId:winner==='draw'?null:winner,forma:method,finalizacao:finish,observacoes:obs})}catch(err){setError(err.message)}}return <form onSubmit={submit}><div className="result-icon"><Trophy/></div><label>Vencedor<select value={winner} onChange={e=>setWinner(e.target.value)}><option value="draw">Empate / sem vencedor</option><option value={a1.id}>{a1.nome}</option><option value={a2.id}>{a2.nome}</option></select></label><label>Forma de vitória<select value={method} onChange={e=>setMethod(e.target.value)}>{['Finalização','Pontos','Decisão','Desclassificação','W.O.','Outra'].map(x=><option key={x}>{x}</option>)}</select></label>{method==='Finalização'?<label>Finalização<input required value={finish} onChange={e=>setFinish(e.target.value)} placeholder="Ex.: Mata-leão"/></label>:null}<label>Observações<textarea value={obs} onChange={e=>setObs(e.target.value)}/></label>{error?<div className="form-error">{error}</div>:null}<div className="form-actions"><button type="button" className="btn ghost" onClick={onCancel}>Cancelar</button><button className="btn primary">Salvar resultado</button></div></form>}
function FightEdit({fight,athletes,onCancel,onSave}){const[data,setData]=useState(fight);const[error,setError]=useState('');async function submit(e){e.preventDefault();if(data.atleta1Id===data.atleta2Id){setError('Selecione atletas diferentes.');return}try{await onSave(data)}catch(err){setError(err.message)}}return <form onSubmit={submit} className="form-grid"><label>Atleta 1<select value={data.atleta1Id} onChange={e=>setData({...data,atleta1Id:e.target.value})}>{athletes.map(a=><option value={a.id} key={a.id}>{a.nome}</option>)}</select></label><label>Atleta 2<select value={data.atleta2Id} onChange={e=>setData({...data,atleta2Id:e.target.value})}>{athletes.map(a=><option value={a.id} key={a.id}>{a.nome}</option>)}</select></label><label>Modalidade<select value={data.modalidade} onChange={e=>setData({...data,modalidade:e.target.value})}><option>Gi</option><option>No-Gi</option></select></label><label>Estilo<input value={data.estilo} onChange={e=>setData({...data,estilo:e.target.value})}/></label><label>Status<select value={data.status} onChange={e=>setData({...data,status:e.target.value})}><option>Agendada</option><option>Finalizada</option></select></label><label className="span-2">Observações<textarea value={data.observacoes} onChange={e=>setData({...data,observacoes:e.target.value})}/></label>{error?<div className="form-error span-2">{error}</div>:null}<div className="form-actions span-2"><button type="button" className="btn ghost" onClick={onCancel}>Cancelar</button><button className="btn primary">Salvar alterações</button></div></form>}
